In [2]:
import numpy as np

In [2]:
# Set seed for reproducibility
np.random.seed(seed=1234)

In [3]:
# Scalar - (0D tensor) - a single value
x = np.array(6)
print("x: ", x)
print("x ndim: ", x.ndim)   # number of dimensions
print("x shape: ", x.shape) # dimensions
print("x size: ", x.size)   # size of elements
print("x dtype: ", x.dtype) # data type

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [5]:
# Vector - (1D tensor) - row or column of values
x = np.array([1.3, 2.2, 1.7])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [1.3 2.2 1.7]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [6]:
# Matrix - (2D tensor) - array (rows and columns of values)
x = np.array([[1, 2], [3, 4]])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype) 

x:  [[1 2]
 [3 4]]
x ndim:  2
x shape:  (2, 2)
x size:  4
x dtype:  int64


In [8]:
# 3D tensor
x = np.array([
    [[1, 2], [3, 4]],           # First 2x2 matrix
    [[5, 6], [7, 8]]            # Second 2x2 matrix
    ])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [6]:
# 4D tensor   [common in Convolutional Neural Networks(CNN)]
x = np.array([
    [
        [[1, 2], [3, 4]],  # First 2x2 matrix
        [[5, 6], [7, 8]]   # Second 2x2 matrix
    ],
    [
        [[9, 10], [11, 12]],  # Third 2x2 matrix
        [[13, 14], [15, 16]]  # Fourth 2x2 matrix
    ]
])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
x ndim:  4
x shape:  (2, 2, 2, 2)
x size:  16
x dtype:  int64
