# Lab 03 - NumPy Library (Part 1) - Andrew Badzioch

What is NumPy Library?
1. It is a Python library for processing numeric data type (dtype).
2. It was created in 2005.
3. The core of NumPy is called "array" which is a collection of data.
4. An array is very similar to a Python list, but an array is a lot faster (50 times faster).
5. An array can be multidimentional, where as a list is one-dimentional (1D).
6. The best source for NumPy is: https://numpy.org/

### 1. Installing and importing NumPy

In [1]:
# to install NumPy
!pip install numpy

In [2]:
# Let's import numpy
import numpy as np  # np is the alias name for numpy

In [3]:
# Let's check the version of numpy
print(np.__version__)

1.26.4


### 2. Creating NumPy Arrays (ndarray) from scratch
- NumPy standard numeric data types
1. int
2. float
3. Boolean (bool)
4. complex

In [4]:
# 1. Creating an array using a Python list and the array() method.
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
type(a)

numpy.ndarray

In [7]:
# 2. Using a tuple 
b = np.array((1, 2, 3, 4))
b

array([1, 2, 3, 4])

In [8]:
type(b)

numpy.ndarray

In [9]:
print(b)

[1 2 3 4]


In [10]:
# 3. Using the zeros()
c = np.zeros(5, dtype=int)
c

array([0, 0, 0, 0, 0])

In [11]:
# 4. Using the ones()
d = np.ones(5, dtype=float)
d

array([1., 1., 1., 1., 1.])

In [12]:
# Let's use the arange() method: the last value is excluded from bein displayed
e = np.arange(0, 11)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# Let's use the arange() method: the last value is excluded from bein displayed using a step
f = np.arange(0, 11, 2)
f

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# Let's use the arange() method: the last value is excluded from bein displayed using a step
g = np.arange(0, 11, 3)
g

array([0, 3, 6, 9])

In [15]:
# using the random.randint()
h = np.random.randint(9, size=7)
h

array([1, 6, 2, 8, 1, 7, 8])

In [16]:
print("ndim: ", h.ndim)

ndim:  1


**Observations:**
- np.array(): method that is flexible and converts a list, tuple, and other sequences into an ndarray, allowing the creation of arrays from any sequence type.
- np.zeros(): creates a ndarray filled with zeros, allowing you fill with data at a later point.
- np.ones(): similar to np.zeros(), but initializes with ones.
- np.arange(): creates a ndarray with spaced values within a specified range


### 3. NumPy array dimentionality
1. 1D: this type of array, has only one dimension. (vector) 
2. 2D: we can see rows and columns in this type of arrays. (matrix)
3. 3D: rows, columns, and depth in this type of arrays

In [17]:
# h is 1D array
h


array([1, 6, 2, 8, 1, 7, 8])

In [18]:
# 2D array
i = np.random.randint(15, size=(3, 4))
i

array([[14, 12,  5,  3],
       [ 7,  4,  3,  4],
       [ 8,  6, 12, 11]])

In [19]:
i.ndim

2

In [20]:
# 3D array
j = np.random.randint(15, size=(3, 4, 2))
j

array([[[13,  1],
        [ 9, 14],
        [10,  6],
        [ 5, 13]],

       [[ 8,  0],
        [ 1,  3],
        [ 9,  4],
        [ 7,  2]],

       [[ 4,  3],
        [ 1,  3],
        [ 8,  6],
        [10, 14]]])

In [21]:
j.ndim

3

In [22]:
# create a 2D array filling it with name
k = np.full((3, 5), 'andy')
k
# U4 stands for unicode and the number of name character

array([['andy', 'andy', 'andy', 'andy', 'andy'],
       ['andy', 'andy', 'andy', 'andy', 'andy'],
       ['andy', 'andy', 'andy', 'andy', 'andy']], dtype='<U4')

#### 4. Dimensionality and the reshape() method

In [23]:
l = np.arange(100)
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
# using reshape() method
m = l.reshape(2, 10, 5)
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [25]:
n = np.array(15, ndmin=5)
n
# ndmin: minimum number of dimensions

array([[[[[15]]]]])

#### 5. Data (Array) Attributes
- Data attributes provide extra and useful information about the data
1. shape: gives the total number of row and columns in a dataset
2. ndim: gives the total number of dimensions of the dataset
3. size: gives the total number of values in a datset (row * columns)
4. columns: gives the number of the columns in the dataset
5. dtypes: gives the different data types in a dataset

In [26]:
m.shape

(2, 10, 5)

In [27]:
m.size

100

In [28]:
m.ndim

3

**Observations:**
- np.full(): Initializes an ndarray with a specified value, which can be useful when a constant array is needed.
- np.reshape(): allows you to change the dimensions wothout modifying the data.


#### 6. Indexing Arrays 

In [29]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    4: 4 elems, type `int64`, 32 bytes
b          ndarray    4: 4 elems, type `int64`, 32 bytes
c          ndarray    5: 5 elems, type `int64`, 40 bytes
d          ndarray    5: 5 elems, type `float64`, 40 bytes
e          ndarray    11: 11 elems, type `int64`, 88 bytes
f          ndarray    6: 6 elems, type `int64`, 48 bytes
g          ndarray    4: 4 elems, type `int64`, 32 bytes
h          ndarray    7: 7 elems, type `int64`, 56 bytes
i          ndarray    3x4: 12 elems, type `int64`, 96 bytes
j          ndarray    3x4x2: 24 elems, type `int64`, 192 bytes
k          ndarray    3x5: 15 elems, type `<U4`, 240 bytes
l          ndarray    100: 100 elems, type `int64`, 800 bytes
m          ndarray    2x10x5: 100 elems, type `int64`, 800 bytes
n          ndarray    1x1x1x1x1: 1 elems, type `int64`, 8 bytes
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


In [30]:
a 

array([1, 2, 3, 4])

In [31]:
# indexing or accessing 4
a[3]

4

In [32]:
a[:3]

array([1, 2, 3])

In [33]:
i

array([[14, 12,  5,  3],
       [ 7,  4,  3,  4],
       [ 8,  6, 12, 11]])

In [34]:
# index [row, column]
i[1, 2]

3

In [35]:
# sort the i array
print(np.sort(i))

[[ 3  5 12 14]
 [ 3  4  4  7]
 [ 6  8 11 12]]


In [36]:
print(np.sort(j))

[[[ 1 13]
  [ 9 14]
  [ 6 10]
  [ 5 13]]

 [[ 0  8]
  [ 1  3]
  [ 4  9]
  [ 2  7]]

 [[ 3  4]
  [ 1  3]
  [ 6  8]
  [10 14]]]


## Conclusion
1. NumPy is a fundamental package for scientific computing in Python, providing support for arrays, matrices, and other mathematical functions to operate on data structures.
2. The core feature of NumPy is the ndarray, supporting multi-dimensional data, allowing efficient storage and manipulation of large datasets.
3. The mathematical functions include statistical, trigonometric, and algebraic operations, that can be applied to entire arrays.
4. Functions for linear algebra include matrix manipulation, inversion, and solving linear systems, which are essential for data science and machine learning.
5. Supports both integer and boolean indexing, accessing elements on an array using square brackets []. To access an element in a multi-dimensional array, you must provide a tuple of indices (one for each domension, ex. np[2, 3], will get the element that is at the 3rd row and 4th column).
6. You can slice an array to access a range of elements within it, allowing you to extract or modify subarrays and specific sections (ex. np[1:4, :2] will include rows 2 to 4 and columns 1 and 2)
7. NumPy arrays are often used as the foundation for other scientific libraries like SciPy, pandas, and TensorFlow, due to their effient handling of large datasets.
8. NumPy arrays have a fixed size at creation and chaning the size will create a new array and delete the original.

#### End of Lab 03