### Creating arrays from scratch

In [1]:
import numpy as np

In [2]:
# create a length 10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# create a 3x5 floating point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# create a 3x5 array filled with whatever
np.full((3,5), 'andy')

array([['andy', 'andy', 'andy', 'andy', 'andy'],
       ['andy', 'andy', 'andy', 'andy', 'andy'],
       ['andy', 'andy', 'andy', 'andy', 'andy']], dtype='<U4')

In [5]:
# create an array filled with linear sequence (start, stop, step)
# similar to the range() function
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# create an array of values evenly space apart between the start and stop
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# create a 3x3 array of random integers in the interval 0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 5, 0],
       [8, 8, 0],
       [0, 8, 0]])

### Basics
- Attributes: (size, shape, data types, memory consumption)
- Indexing: get and set the value of individual elements
- Slicing: get and set smaller subarrays within a larger array
- Reshaping
- Joining and splitting arrays

<code>Attributes</code>

In [8]:
# setting NumPy's random number generator, (seed) will set a value so that the same random arrays are generated each time the code is run
# seed is usually set at 0 or 42, but can be any positive integer
np.random.seed(0)

x = np.random.randint(10, size=(3, 4))