### Creating Arrays from Python Lists

In [1]:
import numpy as np

In [2]:
# integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
# if types don't match, NumPy will upcast to floating point
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
# initializing a multidimensional array
# nested lists result in multidimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# you can explicitly set the data type using a keyword
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

### Creating arrays from scratch

In [6]:
# create a length 10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# create a 3x5 floating point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# create a 3x5 array filled with whatever
np.full((3,5), 'andy')

array([['andy', 'andy', 'andy', 'andy', 'andy'],
       ['andy', 'andy', 'andy', 'andy', 'andy'],
       ['andy', 'andy', 'andy', 'andy', 'andy']], dtype='<U4')

In [9]:
# create an array filled with linear sequence (start, stop, step)
# similar to the range() function
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# create an array of values evenly space apart between the start and stop
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# create a 3x3 array of random integers in the interval 0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 3, 2],
       [5, 0, 2],
       [6, 4, 5]])

### Basics
- Attributes: (size, shape, data types, memory consumption)
- Indexing: get and set the value of individual elements
- Slicing: get and set smaller subarrays within a larger array
- Reshaping
- Joining and splitting arrays

<code>Attributes</code>

In [12]:
# setting NumPy's random number generator, (seed) will set a value so that the same random arrays are generated each time the code is run
# seed is usually set at 0 or 42, but can be any positive integer
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [13]:
print('dtype: ', x3.dtype)

dtype:  int64


In [14]:
print('itemsize: ', x3.itemsize, 'bytes')
print('nbytes: ', x3.nbytes, 'bytes')

itemsize:  8 bytes
nbytes:  480 bytes


#### Array Indexing: Accessing Single Elements

In [15]:
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
x1[0]

5

In [17]:
x1[4]

7

In [18]:
x1[-1]

9

In [19]:
# in multidimensional arrays, access items using a comma-separated tuple of indices
x2[0, 0]

3

In [20]:
x2[2, 0]

1

In [21]:
# modify values using any of the above indexing notation
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### Array Slicing: Accessing Subarrays
- x[start:stop:step]